config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :equipment
  resources :employees

  root 'equipment#show'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign_to.rb
class AssignTo < ApplicationRecord
	validate :employee_name, presence: true
	validate :department, presence: true

	belongs_to  :equipment
end

app/models/employees.rb
class Employee < ApplicationRecord
	validate :employee_name, presence: true
	validate :department, presence: true

	belongs_to  :equipment
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  validates :status, presence: true
  validates :employee, presence: true
  validates :equipment_type, presence: true
  validates :serial_no, presence: true
  validates :name, presence: true

  has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :before_checks, :only [:show, :edit, :update, :destroy ]

	def index
		@employees = Employees.all
	end

	def show 
		empoloyees.show
	end

	def new
		@employees = Employee.new
	end

	def create
	end

	def edit 
		employees.edit
	end

	def update
		@employees = Employees.update
	end

	def destroy
		employee.destroy
	end

	private
	def employee_params
		params.require(:employees).permit(:first_name, :last_name, :department)
	end


	def before_checks 
		@employees = Employees.find(params[:id])
	end


end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
	 before_action :before_checks, only: [ :update, :destroy]

	def index
		@equipment = Equipment.all
	end

	def show
		@equipment = Equipment.all
	end

	def new
		@equipment = Equipment.new
	end

	def create
		@equipment = Equipment.create(equipment_params)
		respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'New item of equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
		@equipment = Equipment.find(params[:id])
	end

	def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end




	def destroy
		@equipment.destroy 
		respond_to do |format|
    	format.html { redirect_to equipment_url, notice: 'Item successfully deleted.' }
    end
	end

	private
	def equipment_params
      params.require(:equipment).permit(:name, :equipment_type, :serial_no, :status, :employee)
  end

  def before_checks
  	@equipment = Equipment.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/employees/edit.html.erb
<h2> EMPLOYEES EDIT VIEW </h2>

app/views/employees/index.html.erb
<h2> EMPLOYEE INDEX VIEW </h2>

app/views/employees/new.html.erb
<h2> EMPLOYEES NEW VIEW </h2>

app/views/employees/show.html.erb
<h2> EMPLOYEES SHOW VIEW </h2>

app/views/equipment/_form.html.erb
<%= form_for Equipment.new do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :equipment_type %>
    <%= f.text_field :equipment_type %>
  </div>
  <br>
  <div class="field">
    <%= f.label :serial_no %>
    <%= f.text_field :serial_no %>
  </div>
  <br>
  <div class="field">
    <%= f.label :employee %>
    <%= f.text_field :employee %>
  </div>
  <br>
  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'View All Equipment', new_equipment_path %>

app/views/equipment/edit.html.erb
<h1> EDIT VIEW</h1>

<h3> Edit Equipment fields here</h3>

<%= form_for(@equipment) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :equipment_type %>
    <%= f.text_field :equipment_type %>
  </div>
  <br>
  <div class="field">
    <%= f.label :serial_no %>
    <%= f.text_field :serial_no %>
  </div>
  <br>
  <div class="field">
    <%= f.label :employee %>
    <%= f.text_field :employee %>
  </div>
  <br>
  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'View All Equipment', @equipment %>

app/views/equipment/index.html.erb
<h1> GetSmarter | Equipment </h1> 
<h3> INDEX VIEW </h3>

<%= link_to 'Add New Equipment', new_equipment_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Serial Number</th>
      <th>Employee</th>
      <th>Status</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td><%= equipment.name %></td>
        <td><%= equipment.equipment_type %></td>
        <td><%= equipment.serial_no %></td>
        <td><%= equipment.employee %></td>
        <td><%= equipment.status %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
        <td><%= link_to 'Delete', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    
  </tbody>
</table>

  


<br>

<% end %>

app/views/equipment/new.html.erb
<h1> NEW VIEW </h1>

<h3> Add New Equipment </h3>

<%= form_for(@equipment) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :equipment_type %>
    <%= f.text_field :equipment_type %>
  </div>
  <br>
  <div class="field">
    <%= f.label :serial_no %>
    <%= f.text_field :serial_no %>
  </div>
  <br>
  <div class="field">
    <%= f.label :employee %>
    <%= f.text_field :employee %>
  </div>
  <br>
  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'View All Equipment', @equipment %>

app/views/equipment/show.html.erb
<h1> GetSmarter | Equipment </h1> 
<h2> SHOW | List of Equipment </h2> 

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Serial Number</th>
      <th>Employee</th>
      <th>Status</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
     <% @equipment.each do |equip| %>
      <tr>
        <td><%= equip.name %></td>
        <td><%= equip.equipment_type %></td>
        <td><%= equip.serial_no %></td>
        <td><%= equip.employee %></td>
        <td><%= equip.status %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equip) %></td>
        <td><%= link_to 'Delete', equip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<%= link_to 'Add New Equipment', new_equipment_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssetManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
    <%= yield %>
  </body>
</html>